ARG IMAGE_TAG=v1.61.0-noble
FROM mcr.microsoft.com/playwright:$IMAGE_TAG

RUN  mkdir /scraper && cd /scraper && npm init -y && npm install playwright winston winston-daily-rotate-file
COPY ./scraper.js /scraper/

WORKDIR /scraper

COPY ./entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "node", "scraper.js" ]

